SELECT * FROM housing_inspections.`public_housing_inspection_data`;
create table one as
SELECT PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME, 
STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS MR_INSPECTION_DATE, COST_OF_INSPECTION_IN_DOLLARS AS 
MR_INSPECTION_COST,
LEAD(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY 
PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE,
LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY 
PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST,
COST_OF_INSPECTION_IN_DOLLARS - (LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME 
ORDER BY PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC)) AS CHANGE_IN_COST,
((COST_OF_INSPECTION_IN_DOLLARS - (LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME 
ORDER BY PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC)))/(LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY 
PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC))) * 100 AS PERCENT_CHANGE_IN_COST,
ROW_NUMBER() OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME 
ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC) AS 
INSPECTION_ID from public_housing_inspection_data;
select * from one;

create table two as
select PHA_NAME,MR_INSPECTION_DATE,MR_INSPECTION_COST,SECOND_MR_INSPECTION_DATE,SECOND_MR_INSPECTION_COST,CHANGE_IN_COST,PERCENT_CHANGE_IN_COST
from one
 where INSPECTION_ID =1 and PERCENT_CHANGE_IN_COST > 0;
select * from two;

